import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {ASSETS,ENEMIES,ITEMS,NPCS} from '../data/gameData.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export class GameRuntime{
 constructor(mount,onEvent){this.mount=mount;this.onEvent=onEvent;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#07090d');this.scene.fog=new THREE.Fog('#07090d',35,105);this.camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,240);this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.setSize(innerWidth,innerHeight);mount.appendChild(this.renderer.domElement);this.clock=new THREE.Clock();this.loader=new GLTFLoader();this.assets=new Map();this.enemies=[];this.npcs=[];this.interactables=[];this.keys={};this.attackCooldown=0;this.dodgeCooldown=0;this.abilityCooldown=0;this.player={group:null};this.state=null;this.setup();}
 setup(){const hemi=new THREE.HemisphereLight('#b7c8e8','#24160e',1.7);this.scene.add(hemi);const sun=new THREE.DirectionalLight('#ffd89a',2.3);sun.position.set(-25,35,15);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-55;sun.shadow.camera.right=55;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;this.scene.add(sun);this.buildGround();this.buildWorld();this.bind();this.loop();}
 buildGround(){const ground=new THREE.Mesh(new THREE.PlaneGeometry(120,120),new THREE.MeshStandardMaterial({color:'#202721',roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;this.scene.add(ground);const grid=new THREE.GridHelper(120,60,'#334037','#202a24');grid.position.y=.01;grid.material.opacity=.2;grid.material.transparent=true;this.scene.add(grid);}
 mat(c,r=.8){return new THREE.MeshStandardMaterial({color:c,roughness:r});}
 box(x,y,z,sx,sy,sz,c){const m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),this.mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;this.scene.add(m);return m;}
 tree(x,z,s){const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.2*s,.32*s,1.8*s,7),this.mat('#4b3828'));trunk.position.y=.9*s;trunk.castShadow=true;g.add(trunk);for(let i=0;i<3;i++){const crown=new THREE.Mesh(new THREE.ConeGeometry((1.15-i*.18)*s,(2.5-i*.2)*s,7),this.mat(i===0?'#253b2b':i===1?'#2d4630':'#38543a'));crown.position.y=(2.2+i*.8)*s;crown.castShadow=true;g.add(crown);}g.position.set(x,0,z);this.scene.add(g);}
 buildWorld(){for(let i=0;i<80;i++){const x=(Math.random()-.5)*105,z=(Math.random()-.5)*105;if(Math.hypot(x,z)>10)this.tree(x,z,.6+Math.random()*.8);}this.road(0,8,5,38);this.road(0,-25,28,4);this.road(-22,-20,20,4);this.ruins(28,18);this.beacon(0,-38);this.grove(-28,-20);this.voidGate(38,-32);this.camp(-3,6);}
 road(x,z,length,width){this.box(x,.03,z,width,.06,length,'#34332f');}
 ruins(x,z){for(let i=0;i<8;i++){const a=i*Math.PI/4,r=5+Math.random()*5;this.box(x+Math.cos(a)*r,1.4,z+Math.sin(a)*r,.9,2.8,.9,'#4a4b4a');}this.box(x,.4,z,8,.8,8,'#363a37');this.interactable('ruins',x,z,'Search the Forgotten Ruins');}
 beacon(x,z){this.box(x,.5,z,7,1,7,'#3b3a37');this.box(x,3,z,2,5,2,'#584638');const ring=new THREE.Mesh(new THREE.TorusGeometry(2.1,.18,8,32),this.mat('#b87437',.4));ring.rotation.x=Math.PI/2;ring.position.set(x,5.7,z);this.scene.add(ring);this.interactable('beacon',x,z,'Restore Beacon');}
 grove(x,z){for(let i=0;i<12;i++){const a=i*Math.PI/6,r=5+Math.random()*5;this.tree(x+Math.cos(a)*r,z+Math.sin(a)*r,1+Math.random()*.5);}const shrine=new THREE.Mesh(new THREE.CylinderGeometry(2.2,2.8,.6,10),this.mat('#3f4740'));shrine.position.set(x,.3,z);this.scene.add(shrine);this.interactable('grove_shrine',x,z,'Cleanse Shrine');}
 voidGate(x,z){for(const dx of [-4,4])this.box(x+dx,3,z,1.4,6,1.4,'#44304f');this.box(x,6,z,10,1.2,1.2,'#5d376b');const light=new THREE.PointLight('#9d4cff',3,16);light.position.set(x,4,z);this.scene.add(light);this.interactable('void',x,z,'Enter Void Scar');}
 camp(x,z){this.box(x,.35,z,7,.7,5,'#302f2a');const fire=new THREE.PointLight('#ff9c43',2.5,12);fire.position.set(x,1,z);this.scene.add(fire);const flame=new THREE.Mesh(new THREE.ConeGeometry(.55,1.5,7),this.mat('#d85b2d'));flame.position.set(x,.9,z);this.scene.add(flame);}
 interactable(id,x,z,label){const orb=new THREE.Mesh(new THREE.SphereGeometry(.28,10,10),this.mat('#d8ad52',.35));orb.position.set(x,1.2,z);this.scene.add(orb);this.interactables.push({id,label,mesh:orb,x,z,used:false});}
 bind(){this.kd=e=>{this.keys[e.key.toLowerCase()]=true;if(e.code==='Space')this.attack();if(e.key.toLowerCase()==='shift')this.dodge();if(e.key.toLowerCase()==='e')this.interact();if(['1','2','3','4','5'].includes(e.key))this.useAbility(Number(e.key)-1)};this.ku=e=>{this.keys[e.key.toLowerCase()]=false};addEventListener('keydown',this.kd);addEventListener('keyup',this.ku);addEventListener('resize',()=>this.resize());this.renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===0)this.attack()});}
 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);}
 async load(key,url,scale=1){if(this.assets.has(key))return this.assets.get(key);return new Promise(resolve=>this.loader.load(url,g=>{g.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});g.scene.scale.setScalar(scale);this.assets.set(key,g);resolve(g)},undefined,()=>resolve(null)));}
 async spawnNPC(npc){const base=await this.load(npc.asset,ASSETS[npc.asset],1);const group=base?base.scene.clone(true):new THREE.Group();if(!base)group.add(this.box(0,1,0,.7,2,.5,'#777'));group.position.set(npc.position[0],npc.position[1],npc.position[2]);group.userData={npc};this.scene.add(group);this.npcs.push({npc,group});}
 async spawnEnemy(type,x,z,scale=1){const d=ENEMIES[type];const base=await this.load('skeleton',ASSETS.skeleton,.95);const group=base?base.scene.clone(true):new THREE.Group();if(!base)group.add(this.box(0,1,0,.7,2,.5,d.color));group.position.set(x,0,z);this.scene.add(group);const enemy={type,data:d,group,hp:d.hp*scale,maxHp:d.hp*scale,attackTimer:0,dead:false};this.enemies.push(enemy);return enemy;}
 async init(state){this.state=state;this.player.group=new THREE.Group();this.player.group.position.set(...state.player.position);this.scene.add(this.player.group);const base=await this.load('ranger',ASSETS.ranger,1.05);if(base)this.player.group.add(base.scene.clone(true));else this.player.group.add(this.box(0,1,0,.7,2,.5,'#151922'));for(const npc of NPCS)await this.spawnNPC(npc);for(const p of [['skeleton',-12,-10,1],['skeleton',10,-15,1],['skeleton',15,-4,1],['archer',-18,-25,1],['beast',-24,-12,1],['beast',-31,-23,1],['mage',24,10,1.1],['elite',30,22,1.2]])await this.spawnEnemy(...p);await this.spawnEnemy('elite',-28,-18,2.2);const boss=await this.spawnEnemy('elite',38,-30,3.8);boss.type='void';boss.data={...ENEMIES.elite,id:'void_guardian',name:'Abyssal Warden',hp:700,damage:35,defense:18,speed:1.5,aggro:30,range:3,xp:1200,gold:[500,900],drops:[['void_heart',1]],color:'#7c3fa0'};boss.hp=700;boss.maxHp=700;this.onEvent({type:'ready'});}
 derived(){const p=this.state.player;let damage=10+p.stats.strength*1.8,defense=p.stats.defense,speed=5+p.stats.agility*.12,maxHp=80+p.stats.vitality*12,range=3.2,crit=.05,dodge=.03,reduction=0;const skills=globalThis.__AF_DATA?.SKILLS||{};for(const id of p.skills){const sk=skills[id];if(!sk)continue;if(sk.effect==='damage')damage+=sk.value;if(sk.effect==='defense')defense+=sk.value;if(sk.effect==='moveSpeed')speed*=1+sk.value;if(sk.effect==='attackRange')range+=sk.value;if(sk.effect==='dodge')dodge+=sk.value;if(sk.effect==='damageReduction')reduction+=sk.value;}return{damage,defense,speed,maxHp,range,crit,dodge,reduction};}
 attack(){if(!this.state||this.attackCooldown>0)return;const d=this.derived();this.attackCooldown=.5;let target=null,nd=d.range;for(const e of this.enemies){if(e.dead)continue;const n=distance(this.player.group.position,e.group.position);if(n<nd){target=e;nd=n;}}if(!target){this.onEvent({type:'swing'});return;}let dmg=d.damage*(Math.random()<d.crit?2:1);dmg=Math.max(1,Math.round(dmg-target.data.defense*.35));target.hp-=dmg;this.hitFx(target.group.position,dmg);this.onEvent({type:'damage',value:dmg,enemy:target.data.name});if(target.hp<=0)this.killEnemy(target);}
 killEnemy(e){e.dead=true;this.scene.remove(e.group);const [lo,hi]=e.data.gold;const gold=Math.floor(lo+Math.random()*(hi-lo+1));for(const [item,chance] of e.data.drops)if(Math.random()<chance)this.addItem(item,1);this.onEvent({type:'enemyKilled',enemy:e.data.name,xp:e.data.xp,gold});}
 hitFx(pos,dmg){const ring=new THREE.Mesh(new THREE.RingGeometry(.15,.55,16),this.mat('#f3b54d',.25));ring.position.set(pos.x,.8,pos.z);ring.rotation.x=-Math.PI/2;this.scene.add(ring);setTimeout(()=>this.scene.remove(ring),180);this.onEvent({type:'damageNumber',value:dmg,x:pos.x,z:pos.z});}
 dodge(){if(!this.state||this.dodgeCooldown>0)return;this.dodgeCooldown=1.2;const dir=new THREE.Vector3((this.keys.d?1:0)-(this.keys.a?1:0),0,(this.keys.s?1:0)-(this.keys.w?1:0));if(dir.lengthSq()===0)dir.z=-1;dir.normalize();this.player.group.position.addScaledVector(dir,5.5);this.player.group.position.x=clamp(this.player.group.position.x,-54,54);this.player.group.position.z=clamp(this.player.group.position.z,-54,54);this.onEvent({type:'dodge'});}
 useAbility(slot){if(!this.state||this.abilityCooldown>0)return;const id=slot===0?'phantom':'void';const skills=globalThis.__AF_DATA?.SKILLS||{};if(!this.state.player.skills.includes(id))return;this.abilityCooldown=skills[id]?.cooldown||6;if(id==='phantom'){this.dodge();return;}for(const e of this.enemies){if(e.dead)continue;if(distance(this.player.group.position,e.group.position)<6){e.hp-=28;this.hitFx(e.group.position,28);if(e.hp<=0)this.killEnemy(e);}}this.onEvent({type:'ability',name:'Void Pulse'});}
 interact(){if(!this.state)return;let best=null,bd=2.8;for(const o of this.interactables){if(o.used)continue;const d=distance(this.player.group.position,o.mesh.position);if(d<bd){best=o;bd=d}}if(best){best.used=true;if(best.id==='beacon'){this.addItem('beacon_core',1);this.onEvent({type:'objective',id:'beacon',label:'Beacon restored'});}if(best.id==='grove_shrine')this.onEvent({type:'objective',id:'grove_shrine',label:'The shrine is listening'});if(best.id==='ruins')this.onEvent({type:'objective',id:'ruins',label:'The Forgotten Ruins are discovered'});if(best.id==='void')this.onEvent({type:'objective',id:'void',label:'The Void Scar opens'});return;}let npcBest=null,npcDist=2.6;for(const n of this.npcs){const d=distance(this.player.group.position,n.group.position);if(d<npcDist){npcBest=n;npcDist=d}}if(npcBest)this.onEvent({type:'npc',npc:npcBest.npc});}
 addItem(id,qty=1){this.onEvent({type:'item',item:ITEMS[id]?.name||id,id,qty});}
 consume(id){const i=this.state.player.inventory.find(x=>x.id===id);if(!i)return false;const item=ITEMS[id];if(item.type!=='consumable')return false;i.qty--;if(i.qty<=0)this.state.player.inventory=this.state.player.inventory.filter(x=>x!==i);this.onEvent({type:'heal',value:item.heal});return true;}
 loop(){requestAnimationFrame(()=>this.loop());if(!this.state||!this.player.group)return;const dt=Math.min(.033,this.clock.getDelta());this.attackCooldown=Math.max(0,this.attackCooldown-dt);this.dodgeCooldown=Math.max(0,this.dodgeCooldown-dt);this.abilityCooldown=Math.max(0,this.abilityCooldown-dt);const d=this.derived();let dx=(this.keys.d?1:0)-(this.keys.a?1:0),dz=(this.keys.s?1:0)-(this.keys.w?1:0);if(dx||dz){const l=Math.hypot(dx,dz);dx/=l;dz/=l;this.player.group.position.x+=dx*d.speed*dt;this.player.group.position.z+=dz*d.speed*dt;this.player.group.rotation.y=Math.atan2(dx,dz);}this.player.group.position.x=clamp(this.player.group.position.x,-54,54);this.player.group.position.z=clamp(this.player.group.position.z,-54,54);for(const e of this.enemies)this.enemyTick(e,dt);this.camera.position.x+=(this.player.group.position.x-this.camera.position.x)*.08;this.camera.position.z+=(this.player.group.position.z+13-this.camera.position.z)*.08;this.camera.position.y+=(7-this.camera.position.y)*.08;this.camera.lookAt(this.player.group.position.x,1.1,this.player.group.position.z);this.renderer.render(this.scene,this.camera);}
 enemyTick(e,dt){if(e.dead)return;const dist=distance(this.player.group.position,e.group.position);if(dist>e.data.aggro)return;const dir=new THREE.Vector3(this.player.group.position.x-e.group.position.x,0,this.player.group.position.z-e.group.position.z).normalize();if(dist>e.data.range)e.group.position.addScaledVector(dir,e.data.speed*dt);else{e.attackTimer-=dt;if(e.attackTimer<=0){e.attackTimer=e.type==='void'?1.1:1.5;const d=this.derived();const reduced=Math.max(1,e.data.damage-d.defense*.45);if(Math.random()>d.dodge){this.onEvent({type:'playerHit',value:Math.round(reduced*(1-d.reduction))});}}}e.group.rotation.y=Math.atan2(-dir.x,-dir.z);}
 dispose(){removeEventListener('keydown',this.kd);removeEventListener('keyup',this.ku);this.renderer.dispose();this.mount.innerHTML='';}
}
