import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {GameRuntime} from './game/runtime.js';
import {ITEMS,QUESTS,RARITY,SKILLS,STAT_LABELS,ZONES} from './data/gameData.js';
import {loadSave,saveGame,resetSave,exportSave,importSave} from './game/save.js';
import './style.css';
globalThis.__AF_DATA={SKILLS};
function App(){
 const mount=useRef(null),runtime=useRef(null);const [game,setGame]=useState(loadSave);const [menu,setMenu]=useState('');const [dialogue,setDialogue]=useState(null);const [notice,setNotice]=useState('');const [ready,setReady]=useState(false);
 const notify=t=>{setNotice(t);setTimeout(()=>setNotice(''),2200)};const openNPC=npc=>setDialogue({npc,index:0});
 useEffect(()=>{runtime.current=new GameRuntime(mount.current,e=>{if(e.type==='ready')setReady(true);if(e.type==='damage')notify(`${e.enemy} takes ${e.value} damage`);if(e.type==='enemyKilled')setGame(s=>{const q=QUESTS.find(x=>x.id===s.quests.active),progress={...s.quests.progress},map={'Skeleton Warrior':'skeleton','Cinder Hound':'beast','Ash Archer':'archer','Ashen Hexer':'mage','Grave Warden':'elite','Abyssal Warden':'void'};if(q)q.objectives.filter(o=>(o.kind==='kill'&&o.target===map[e.enemy])||(o.kind==='boss'&&o.target===e.target)).forEach(o=>{const k=`${q.id}:${o.id}`;progress[k]=Math.min(o.required,(progress[k]||0)+1)});return {...s,player:{...s.player,xp:s.player.xp+e.xp,gold:s.player.gold+e.gold},quests:{...s.quests,progress}});if(e.type==='item')setGame(s=>{const inv=[...s.player.inventory],i=inv.find(x=>x.id===e.id);if(i)i.qty+=e.qty||1;else inv.push({id:e.id,qty:e.qty||1});return {...s,player:{...s.player,inventory:inv}}});if(e.type==='npc'){openNPC(e.npc);setGame(s=>{const q=QUESTS.find(x=>x.id===s.quests.active);if(!q)return s;const progress={...s.quests.progress};q.objectives.filter(o=>o.kind==='talk'&&o.target===e.npc.id).forEach(o=>progress[`${q.id}:${o.id}`]=o.required);return {...s,quests:{...s.quests,progress}}})}if(e.type==='playerHit')setGame(s=>({...s,player:{...s.player,hp:Math.max(0,s.player.hp-e.value)}}));if(e.type==='death'){notify('You fell. Returning to the frontier camp.');setGame(s=>({...s,player:{...s.player,hp:100,position:[0,0,10]}}));runtime.current.player.group.position.set(0,0,10)}if(e.type==='objective'){notify(e.label);setGame(s=>{const q=QUESTS.find(x=>x.id===s.quests.active),progress={...s.quests.progress};if(q)q.objectives.filter(o=>o.kind==='explore'&&o.target===e.id).forEach(o=>progress[`${q.id}:${o.id}`]=o.required);return {...s,world:{...s.world,opened:[...new Set([...s.world.opened,e.id])]},quests:{...s.quests,progress}}})}if(e.type==='heal')setGame(s=>({...s,player:{...s.player,hp:Math.min(100,s.player.hp+e.value)}}))});runtime.current.init(game);return()=>runtime.current?.dispose()},[]);
 useEffect(()=>{if(runtime.current&&ready){runtime.current.state=game;saveGame(game)}},[game,ready]);
 useEffect(()=>{let xp=game.player.xp,level=game.player.level,pts=game.player.skillPoints;while(xp>=100){xp-=100;level++;pts++}if(level!==game.player.level||xp!==game.player.xp||pts!==game.player.skillPoints){if(level>game.player.level)notify(`Level ${level} reached · +1 Skill Point`);setGame(s=>({...s,player:{...s.player,level,xp,skillPoints:pts}}))}},[game.player.xp]);
 const advance=()=>setDialogue(d=>d&&d.index+1<d.npc.lines.length?{...d,index:d.index+1}:null);const activeQuest=QUESTS.find(q=>q.id===game.quests.active)||QUESTS[0];
 const completeQuest=()=>{const q=activeQuest;if(q.id==='q_intro'){setGame(s=>({...s,quests:{...s.quests,completed:[...s.quests.completed,q.id],active:'q_beacon'}}));notify('Quest complete · The Broken Beacon is now available');return}const ok=q.objectives.every(o=>{const p=game.quests.progress[`${q.id}:${o.id}`]||0;return o.kind==='collect'?game.player.inventory.some(i=>i.id===o.target&&i.qty>0):p>=o.required});if(!ok){notify('Some objectives are still incomplete');return}const next=QUESTS[QUESTS.findIndex(x=>x.id===q.id)+1]?.id||null;setGame(s=>({...s,player:{...s.player,xp:s.player.xp+q.rewards.xp,gold:s.player.gold+q.rewards.gold},quests:{...s.quests,completed:[...s.quests.completed,q.id],active:next}}));notify(`Quest complete · +${q.rewards.xp} XP · +${q.rewards.gold} Gold`)};
 const unlock=id=>{const sk=SKILLS[id];if(!sk||game.player.skills.includes(id)||game.player.skillPoints<sk.cost||sk.requires.some(r=>!game.player.skills.includes(r)))return;setGame(s=>({...s,player:{...s.player,skillPoints:s.player.skillPoints-sk.cost,skills:[...s.player.skills,id]}}));notify(`${sk.name} unlocked`)};
 return <div className="game"><div ref={mount} className="canvas"/>{!ready&&<div className="loading"><div>◆</div><h1>ASHEN FRONTIER</h1><p>Loading the frontier...</p><span/></div>}<header><div><b>ASHEN FRONTIER</b><small>OPEN WORLD · DARK FANTASY RPG</small></div><div className="topstats">LV {game.player.level}<span>{game.player.gold} G</span><span>✦ {game.player.skillPoints}</span></div></header><section className="hud"><label>HP <b>{Math.round(game.player.hp)}</b></label><div className="bar"><i style={{width:`${Math.min(100,game.player.hp)}%`}}/></div><label>XP <b>{game.player.xp}/100</b></label><div className="bar xp"><i style={{width:`${Math.min(100,game.player.xp)}%`}}/></div></section><aside className="quest"><span>ACTIVE QUEST</span><h2>{activeQuest.title}</h2><p>{activeQuest.description}</p><small>{activeQuest.type.toUpperCase()}</small><button onClick={completeQuest}>TURN IN</button></aside><div className="controls"><span>WASD</span><span>SPACE ATTACK</span><span>SHIFT DODGE</span><span>E INTERACT</span></div><div className="mobile"><button onClick={()=>runtime.current?.attack()}>⚔</button><button onClick={()=>runtime.current?.dodge()}>⇢</button><button onClick={()=>runtime.current?.interact()}>E</button></div><nav><button onClick={()=>setMenu('character')}>Character</button><button onClick={()=>setMenu('inventory')}>Inventory</button><button onClick={()=>setMenu('skills')}>Skills <i>{game.player.skillPoints}</i></button><button onClick={()=>setMenu('quests')}>Quests</button><button onClick={()=>setMenu('map')}>Map</button><button onClick={()=>setMenu('settings')}>⚙</button></nav>{notice&&<div className="notice">{notice}</div>}{dialogue&&<div className="dialogue"><div className="portrait">{dialogue.npc.portrait}</div><div><small>{dialogue.npc.role}</small><h2>{dialogue.npc.lines[dialogue.index][0]==='player'?'You':dialogue.npc.name}</h2><p>{dialogue.npc.lines[dialogue.index][1]}</p><button onClick={advance}>{dialogue.index+1<dialogue.npc.lines.length?'CONTINUE':'CLOSE'}</button></div></div>}{menu&&<div className="modal"><button className="close" onClick={()=>setMenu('')}>×</button>{menu==='character'&&<Character game={game}/>} {menu==='inventory'&&<Inventory game={game} setGame={setGame}/>} {menu==='skills'&&<Skills game={game} unlock={unlock}/>} {menu==='quests'&&<Quests game={game} complete={completeQuest}/>} {menu==='map'&&<Map/>} {menu==='settings'&&<Settings game={game} setGame={setGame}/>}</div>}</div>}
function Character({game}){return <><h1>CHARACTER</h1><p>Level {game.player.level} · Frontier Ranger</p><div className="statgrid">{Object.entries(game.player.stats).map(([k,v])=><div key={k}><b>{STAT_LABELS[k]}</b><strong>{v}</strong></div>)}</div><h2>Equipment</h2><div className="equipgrid">{Object.entries(game.player.equipment).map(([slot,id])=><div key={slot}><small>{slot}</small><b>{id?ITEMS[id].name:'Empty'}</b></div>)}</div></>}
function Inventory({game,setGame}){const equip=id=>{const item=ITEMS[id];if(!item.slot)return;setGame(s=>({...s,player:{...s.player,equipment:{...s.player.equipment,[item.slot]:id}}}))};return <><h1>INVENTORY</h1><p>Gold: {game.player.gold}</p><div className="items">{game.player.inventory.map(i=>{const it=ITEMS[i.id];return <div className="item" key={i.id} style={{borderColor:RARITY[it.rarity]}}><span>{it.icon}</span><div><b>{it.name}</b><small>{it.rarity} · x{i.qty}</small></div>{it.slot&&<button onClick={()=>equip(i.id)}>EQUIP</button>}</div>})}</div></>}
function Skills({game,unlock}){return <><h1>SKILL TREE</h1><p>Requirements and costs are enforced by the progression system.</p><div className="skilltree">{Object.values(SKILLS).map(s=><button key={s.id} className={game.player.skills.includes(s.id)?'owned':''} disabled={game.player.skills.includes(s.id)||game.player.skillPoints<s.cost||s.requires.some(r=>!game.player.skills.includes(r))} onClick={()=>unlock(s.id)}><strong>{s.name}</strong><small>{s.kind} · {s.cost} SP</small><em>{s.requires.length?`Requires ${s.requires.join(', ')}`:'Root skill'}</em></button>)}</div></>}
function Quests({game,complete}){return <><h1>QUEST JOURNAL</h1><div className="questlist">{QUESTS.map(q=><div className={game.quests.completed.includes(q.id)?'done':''} key={q.id}><b>{q.title}</b><small>{q.description}</small><span>{game.quests.completed.includes(q.id)?'COMPLETED':q.id===game.quests.active?'ACTIVE':'LOCKED'}</span></div>)}</div><button className="goldBtn" onClick={complete}>TURN IN ACTIVE QUEST</button></>}
function Map(){return <><h1>WORLD MAP</h1><div className="worldmap">{Object.values(ZONES).map(z=><div className="zone" key={z.id} style={{left:`${50+z.center[0]}%`,top:`${50-z.center[1]}%`}}><i style={{background:z.color}}/><span>{z.name}</span></div>)}</div></>}
function Settings({game,setGame}){const reset=()=>{if(confirm('Reset your Ashen Frontier save?'))setGame(resetSave())};return <><h1>SETTINGS</h1><div className="settings"><button onClick={()=>saveGame(game)}>SAVE NOW</button><button onClick={()=>navigator.clipboard?.writeText(exportSave(game))}>COPY SAVE</button><button onClick={()=>{const t=prompt('Paste save code');if(t)try{setGame(importSave(t))}catch{alert('Invalid save')}}}>IMPORT SAVE</button><button onClick={reset}>RESET SAVE</button></div><p>The runtime uses lazy GLB loading and conservative renderer settings for mobile-class GPUs.</p></>}
createRoot(document.getElementById('root')).render(<App/>);
